/*
 version 3.5.74
*/
'use strict';var tnscm_adn;
(function(e,f,E){(function(){var C,F,L,I,O,M;C=function(){function p(){}function c(a,d){var m,B;if(a&&(B=a.length))for(m=0;m<B;m+=1)try{d(a[m],m,a)}catch(b){}}function b(a,d){for(var m=0,B=a.length;m<B;)if(a[m++]===d)return m-1;return-1}function q(a,d){return function(){return a.apply(d,arguments)}}function l(a,d,m){e.addEventListener?a.addEventListener(d,m,!1):e.attachEvent&&a.attachEvent("on"+d,m)}function h(a){function d(){c(h.f,function(a){a()});delete h.f}function m(){"loading"!==f.readyState&&
(d(),f.detachEvent("onreadystatechange",m))}"loading"!==f.readyState?a():h.f?h.f.push(a):(h.f=[a],f.addEventListener?f.addEventListener("DOMContentLoaded",d,!1):f.attachEvent&&f.attachEvent("onreadystatechange",m))}function g(a){function d(){for(g.time=r&&0<r.loadEventStart?new Date(r.loadEventStart):new Date;m.length;)m.shift()(g.time)}var m;g.time?a(g.time):(g.R||(g.R=[],l(e,"load",d)),m=g.R,m.push(a),"complete"===f.readyState&&d())}function z(a){var d={};a&&c(a.split("&"),function(a){a=a.split("=");
d[decodeURIComponent(a[0].toLowerCase())]=decodeURIComponent(a[1])});return d}function v(){var a=f.body,d=f.documentElement,a=a?Math.max(a.scrollHeight,a.offsetHeight,a.clientHeight):0;return Math.max(a,d.scrollHeight,d.offsetHeight,d.clientHeight)}function s(a,d){var m;return f.defaultView&&f.defaultView.getComputedStyle?(d=d.replace(/([A-Z])/g,"-$1").toLowerCase(),(m=f.defaultView.getComputedStyle(a,null))&&m.getPropertyValue(d)):a.currentStyle?a.currentStyle[d]:a.style&&a.style[d]?a.style[d]:null}
function w(a){if(!a)return{top:0,left:0};var d={top:a.offsetTop,left:a.offsetLeft};a=w(a.offsetParent);d.top+=a.top;d.left+=a.left;isNaN(d.top)&&(d.top=E);isNaN(d.left)&&(d.left=E);return d}function n(a){return a.contentDocument||a.contentWindow&&a.contentWindow.document||a.document||null}function y(a,d){for(var m=a.childNodes,B=m.length,b;B--;)if(b=y(m[B],d))return b;return d(a)}var A=["","moz","ms","webkit"],k=e.performance,r=k?k.timing:null,k=function(){if("undefined"==typeof navigator.plugins||
0==navigator.plugins.length)try{return!!new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(a){return!1}else return navigator.plugins["Shockwave Flash"]}();return{ua:p,random:function(){var a=(new Date).valueOf().toString();return parseInt(a.substr(a.length-8,a.length))+Math.round(Math.random()*Math.pow(10,9))},ga:k,trim:function(a){return String.prototype.trim!==E?String.prototype.trim.call(a):a.replace(/^\s+|\s+$/g,"")},a:c,indexOf:b,sa:function(a,d,m){var B,b;m=m||p;if(!a)return!1;b=a.length;
0===b&&m();return b?B=setInterval(function(){var c=10;do{b-=1;if(-1===b){clearInterval(B);m();break}d(a[b],b,a)}while(--c)},4):E},extend:function(a,d,m){var b,c;for(b in d)d.hasOwnProperty(b)&&(c=d[b],a[b]=m&&"function"===typeof c?q(c,a):c)},on:l,i:h,load:g,v:function(a){l(e,"scroll",a);l(e,"resize",a);a()},D:function(a,d){function b(){var m=f[x]||"visible";switch(m){case "hidden":d(m);break;default:a(m)}}var c,x;d=d||p;for(c=0;c<A.length;c++)if(x=A[c]+"VisibilityState",x=x.charAt(0).toLowerCase()+
x.substring(1),f[x]){l(f,A[c]+"visibilitychange",b);"hidden"!==f[x]&&b();return}b()},va:z,ba:function(a){function d(a){var d=!1;c(["link1","clicktag","alink1","url","adress"],function(b){a.hasOwnProperty(b)&&(d=a[b])});return d}var b,B,x=a.childNodes,e=a.parentNode,k="",f={};switch(a.nodeName){case "IMG":for(;e;){if("A"===e.nodeName){b=e.href;break}e=e.parentNode}break;case "OBJECT":c(x,function(a){"PARAM"===a.nodeName&&"flashvars"===a.getAttribute("name").toLowerCase()&&(B=a.getAttribute("value"),
f=z(B.replace(/&amp;/g,"&")),b=d(f))});break;case "EMBED":if(k=a.getAttribute("flashvars"))f=z(k.replace(/&amp;/g,"&")),b=d(f)}try{"string"===typeof b&&(b=decodeURIComponent(b))}catch(g){}return b},qa:v,ka:function(a){for(var d=!1,b=a.getClientRects(),c=v(),e=b.length;e--;)if(a=b[e],0!==a.width&&0!==a.height){if(0<a.top)return a.top<=c;if(0<a.bottom)return a.bottom<=c;d=!0}return d},ra:s,ea:w,J:function(a){var d={w:["paddingLeft","paddingRight","borderLeftWidth","borderRightWidth"],h:["paddingTop",
"paddingBottom","borderTopWidth","borderBottomWidth"]},b,c,e;"svg"==a.nodeName?(b=a.getBoundingClientRect(),b={w:Math.round(b.width),h:Math.round(b.height)}):b={w:a.offsetWidth,h:a.offsetHeight};for(c in b)if(b.hasOwnProperty(c)){if(0<b[c])for(e=d[c].length;e--;)b[c]-=parseInt(s(a,d[c][e]),10)||0;e=b[c]||s(a,"w"===c?"width":"height");/%/.test(e)||(b[c]=parseInt(e,10),isNaN(b[c])&&(b[c]=0))}return b},ca:n,fa:function(){var a=f.body,d=f.documentElement;return"number"===typeof e.pageYOffset?e.pageYOffset:
d&&d.scrollTop?d.scrollTop:a&&a.scrollTop?a.scrollTop:0},$:y,ha:function(a){try{var d=a.getAttribute("src")||"",b=d.indexOf("//"+location.host),c;if((0!==d.indexOf("http")&&0!==d.indexOf("//")||-1<b&&8>b)&&(c=n(a))&&c.getElementById)return!0}catch(e){}return!1},I:function(a){function d(a){-1===b(excludeElements,a)&&excludeElements.push(a)}function e(a){var d=f.createElement("a");d.href=a;return d.href}var k,g,h;if(!a.tagName)return!1;if("OBJECT"===a.tagName){k=a.getAttribute("data");a=a.childNodes;
if(!k)for(g=a.length;g--;)if(h=a[g],"PARAM"===h.nodeName&&"movie"===h.getAttribute("name").toLowerCase())return h.getAttribute("value");for(g=a.length;g--;)if(h=a[g],"PARAM"===h.nodeName&&"flashvars"===h.getAttribute("name").toLowerCase()&&(h=z(h.getAttribute("value").replace(/&amp;/g,"&")),h.video1))try{return decodeURIComponent(h.video1)}catch(l){return h.video1}return k}if("VIDEO"===a.tagName){k=a.childNodes;h=k.length;var r,v;if(!a.canPlayType)return!1;for(g=0;g<h;g++)if(r=k[g],"SOURCE"===r.nodeName&&
(v=r.getAttribute("type"),a.canPlayType(v)))return k=r.getAttribute("src")||!1,c(a.getElementsByTagName("embed"),d),c(a.getElementsByTagName("object"),d),k;return k=a.getAttribute("src")}if("SVG"===a.tagName.toUpperCase())g=a.getElementsByTagName("image"),0<g.length&&(k=g[0].getAttribute("xlink:href"));else{g=(k=a.getAttribute("src"))&&"data:image"==k.substring(0,10);h=k&&(0==k.indexOf("//")||0==k.indexOf("http"));if(null==k||g)return k&&g?F.juke_host[0]||null:null;k=a.getAttribute("src");h||(k=e(k))}return k},
da:function(a){var d={};if(top!=self&&e.addonCMeter&&e.addonCMeter&&addonCMeter.currentValues&&addonCMeter.currentValues.offset){var d=f.documentElement,b=f.getElementsByTagName("body")[0],d={w:e.innerWidth||d.clientWidth||b.clientWidth,h:e.innerHeight||d.clientHeight||b.clientHeight};return 10>=Math.abs(d.w-a.w)&&10>=Math.abs(d.h-a.h)?addonCMeter.currentValues.offset:0}return 0},r:function(){var a=F;return e.addonCMeter&&addonCMeter.config&&addonCMeter.config.region||a.region||"ua"}}}();F=function(f){var c=
{source:"source.mmi.bemobile.ua",juke_host:["pa.tns-ua.com/bug/pic.gif","juke.mmi.bemobile.ua/bug/pic.gif"],host:"pagestat.mmi.bemobile.ua",sslhost:"sslpagestat.mmi.bemobile.ua",err_host:"er.mmi.bemobile.ua",timer:{frequency:5,pings:[5,15,30,60,120],stop_after:5},ads:{scan_frequency:5,width:50,height:40},video:{url:"vplayer.mmi.bemobile.ua/vplayer/html5"}};f.extend(c,e.addonCMeter&&addonCMeter.config);c.custom_url&&location.host===c.custom_url.href?(c.ads.scan_frequency=c.custom_url.banner_scan_frequency,
c.work_in_frame=c.custom_url.work_in_frame):c.work_in_frame=!0;"string"===typeof c.juke_host&&(c.juke_host=[c.juke_host]);return c}(C);L=function(p,c){function b(a){var d;try{e.XDomainRequest?(d=new e.XDomainRequest,a&&(d.onerror=function(){a.call(null,d)})):(d=new XMLHttpRequest,a&&(d.onreadystatechange=function(){4==d.readyState&&200!=d.status&&a.call(null,d)}))}catch(b){console.error("cors:"+b)}return d}function q(a,d,b){var c="&";-1==a.indexOf("?")&&(c="?");return a+(c+d+"="+b)}function l(){for(var a=
[],d=0;32>d;d++)a[d]="0123456789ABCDEF".substr(Math.floor(16*Math.random()),1);a[12]="4";a[16]="0123456789ABCDEF".substr(a[16]&3|8,1);return a.join("")}function h(a,d,b){f.cookie=a+"="+escape(d)+(b?"; expires="+b:"")+"; path=/"}function g(a){var b=" "+f.cookie;a=" "+a+"=";var c=null,k=0,e=0;0<b.length&&(k=b.indexOf(a),-1!=k&&(k+=a.length,e=b.indexOf(";",k),-1==e&&(e=b.length),c=unescape(b.substring(k,e))));return c}function z(a){f.cookie=a+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT;"}function v(){var a;
try{a=f.getElementsByTagName("body")[0]}catch(b){}"undefined"!=typeof a&&null!=a||"undefined"==typeof f.body||(a=f.body);return a}e.idCoreOnReady=function(a){r.onFlashReady(a)};e.tnsOnStatResult=function(a){console.log("result:"+a.result+" pid:"+a.wa+" e.id: "+a.id)};var s;try{s="localStorage"in e&&null!==e.localStorage}catch(w){s=!1}var n=function(){if("undefined"==typeof navigator.plugins||0==navigator.plugins.length)try{return!!new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(a){return!1}else return navigator.plugins["Shockwave Flash"]}(),
y=/MSIE/.test(navigator.userAgent),A=function(){var a=navigator.cookieEnabled?!0:!1;"undefined"!=typeof navigator.cookieEnabled||a||(f.cookie="testcookie",a=-1!=f.cookie.indexOf("testcookie")?!0:!1,z("testcookie"));return a}(),k=function(){var a="l";n?a="b":e.postMessage&&(s||A)?a="d":0==s&&0==A&&(a="g");try{if(e.chrome)for(var b in navigator.plugins)if(/PepperFlashPlayer/gi.test(navigator.plugins[b].filename)){a="c";break}}catch(c){console.warn("chrome : PepperFlashPlayer - has some error")}return a}(),
r=function(){function a(){function a(){var b;try{b=new CrossDomainStorage(N,"/cm/3.5.74/cm.html"),b.requestValue(t.id,function(a,b){w(b)})}catch(d){console.error("cds.js:"+d),u=l(),w(u)}}"undefined"===typeof CrossDomainStorage?c.j(G+"/cm/3.5.74/cds.js",a):a()}function d(){var a=new Date;a.setFullYear(a.getFullYear()+1);h(t.wasMigrated,!0,a.toUTCString());w(u)}function m(){return g(t.wasMigrated)?!1:A&&g(t.wasInitialized)?(u=g(t.id),s?(c.j(G+"/id-core/1.77-r59654/cds.js",function(){try{(new CrossDomainStorage(N,
"/id-core/1.77-r59654/id.html")).requestValue(t.id+":"+u,function(a,b){b!=u?console.error("id: "+b+" != "+u):d()})}catch(a){console.error("migrate:"+a)}}),z(t.id),z(t.wasInitialized)):n&&(e.tns_uid=u,c.j(G+"/id-core/1.77-r59654/flash.js",function(){d()})),!0):!1}function r(){S=!0;m()||(s?(u=localStorage.getItem(t.id))?w(u):e.postMessage&&!e.JSON&&e.localStorage?c.j(G+"/json2.min.js",function(){v()?a():c.ready(function(){a()})}):e.postMessage&&e.JSON&&e.localStorage?v()?a():c.ready(function(){a()}):
w(l()):n?v()?c.j(G+"/id-core/1.77-r59654/flash.js"):c.ready(function(){c.j(G+"/id-core/1.77-r59654/flash.js")}):((u=g(t.id))||(u=l()),w(u)))}function x(){for(var a in D)if(D.hasOwnProperty(a)){var b=D[a].url,d=D[a].params,c=D[a].time,k=D[a].type,e=D[a].onError;/^POST$/gi.test(k)?Q(b,d,c,e):R(b,d,c,k,e)}D=[];for(var g in H)H.hasOwnProperty(g)&&H[g].call(this,u);H=[]}function w(a){var b=K.length;u=a;if(s)localStorage.setItem(t.id,a);else if(A){var d=new Date;d.setFullYear(d.getFullYear()+1);h(t.id,
a,d.toGMTString());h(t.wasInitialized,!0,d.toGMTString())}J=!0;x();if(s){if(!localStorage.getItem(t.flag)){for(;b--;)(new Image).src=location.protocol+"//"+K[b]+"?uid="+a+"&time="+(new Date).valueOf();localStorage.setItem(t.flag,"true")}}else if(A&&!g(t.flag)){d=new Date;d.setFullYear(d.getFullYear()+1);for(h(t.flag,"true",d.toGMTString());b--;)(new Image).src=location.protocol+"//"+K[i]+"?uid="+a+"&time="+(new Date).valueOf();localStorage.setItem(t.flag,"true")}}function P(a,b){var d,c;if(b instanceof
Array)for(d in b)a=q(a,b[d].key,b[d].value);else for(c in b)a=q(a,c,b[c]);return a}function Q(a,d,c,k){try{var e=b(k);e.open("POST",a,!0);d||(d={});d instanceof Array?(d.push({key:"cookie",value:u}),d.push({key:"time",value:c?c:(new Date).valueOf()})):(d.cookie=u,d.time=c?c:(new Date).valueOf());y?e.contentType="text/plain":e.setRequestHeader("Content-type","application/x-www-form-urlencoded;charset=UTF-8");var g=P("?",d).replace(/^\?/,"");e.send(g)}catch(h){console.error(h)}}function R(a,d,c,k,g){d||
(d={});a=q(a,"cookie",u);a=q(a,"time",c?c:(new Date).valueOf());a=P(a,d);try{if(k&&"JSONP"==k||e.opera&&!("withCredentials"in new XMLHttpRequest)){var h=f.createElement("script");h.setAttribute("src",a);f.getElementsByTagName("head")[0].appendChild(h)}else{var m=b(g);m.open("GET",a,!0);0==y&&m.setRequestHeader("Accept","application/json");m.send()}}catch(r){console.log(r)}}var J=!1,N=location.protocol+"//"+(p.source||"source.mmi.bemobile.ua"),G=e.addonCMeter&&addonCMeter.hostAddon||N,T="1.77-r59654".replace(/-r\d+$/,
""),K=["pa.tns-ua.com/bug/pic.gif","juke.mmi.bemobile.ua/bug/pic.gif"];try{p&&p.juke_host&&(K=p.juke_host)}catch(C){console.warn(C)}var t={id:"vplayer_user_id",wasInitialized:"tns_was_initialized",wasMigrated:"tns_was_migrated",flag:"flag"},S=!1,D=[],u="",H=[];return{init:function(){0==S?A&&!g(t.wasMigrated)?v()?r():c.ready(function(){r()}):r():J&&x()},send:function(a,b,d,c){b||(b={});b.vt=k;var e=(new Date).valueOf();J?/^POST$/gi.test(d)?Q(a,b,e,c):R(a,b,e,d,c):D.push({url:a,params:b,type:d,time:e,
onError:c})},onFlashReady:function(a){try{var b=f.getElementById("div_holder");b.parentNode.removeChild(b)}catch(d){}swfobjectlite=null;w(a)},addOnReadyListener:function(a){H.push(a)},isReady:function(){return J},getId:function(){return u},version:function(){return T}}}();e.IDCore=e.IDCore||r;r.init();return r}(F,function(e){var c={j:function(b,c){function l(b){h.onload=h.onerror=h.onreadystatechange=null;c&&"function"==typeof c&&c(b)}var h=f.createElement("script"),g=f.head||f.getElementsByTagName("head")[0];
e.extend(h,{async:!0,type:"text/javascript",onload:function(){l(null)},onerror:l,onreadystatechange:function(){"loaded"!==h.readyState&&"complete"!==h.readyState||l(null)}});h.src=b;g.insertBefore(h,g.lastChild)},i:function(b){function e(){each(c.i.f,function(b){b()});delete c.i.f}function l(){"loading"!==f.readyState&&(e(),f.detachEvent("onreadystatechange",l))}"loading"!==f.readyState?b():c.i.f?c.i.f.push(b):(c.i.f=[b],f.addEventListener?f.addEventListener("DOMContentLoaded",e,!1):f.attachEvent&&
f.attachEvent("onreadystatechange",l))},ready:function(b){c.i(b)}};return c}(C));I=function(f){function c(c,e){b[c]||(b[c]=[]);b[c].push(e)}var b={};return{xa:b,c:function(q,l){e.cm_events&&e.cm_events.join?f.a(e.cm_events,function(b,g){b&&b.event==q&&(c(q,b.callback),delete e.cm_events[g])}):e.cm_events=[];f.a(b[q],function(b){l=b.call(this,l)});return l},on:c}}(C);O=function(p,c,b,q){function l(g,f){var h=this,l=top!==self;c.on(e,"beforeunload",function(){h.pa=!0});2<=arguments.length&&c.extend(this,
f,!0);this.b=this.b||[];this.b[0]="~cm_"+g+"~";setTimeout(function(){function f(l){"AddonCMeterReady"===l.data&&(e.removeEventListener("message",f,!1),c.extend(q,e.addonCMeter&&addonCMeter.config),M.na(b.c("templates:yes",[]),b.c("templates:no",[])),h.t(b.c("init_"+g)))}var n=l?"AddonCMeterFrame":"AddonCMeterMain";e.localStorage&&"initializing"===localStorage.getItem(n)||e.sessionStorage&&"initializing"===sessionStorage.getItem(n)||e.sessionStorage&&"initializing"===sessionStorage.getItem("AddonCMeter")?
e.addEventListener("message",f,!1):h.t(b.c("init_"+g))},20)}var h="3.5.74_"+c.r()+"/"+p.version();c.extend(l.prototype,{C:"GET",origin:location.protocol+"//"+("https:"===location.protocol?q.sslhost:q.host),oa:c.random(),U:function(){return e.addonCMeter&&addonCMeter.currentValues&&addonCMeter.currentValues.sid||this.oa},aa:function(){var b={location:encodeURIComponent(e.location.href),referrer:encodeURIComponent(this.referrer||f.referrer),is_flash:c.ga?"1":"0",session_id:this.U(),version:h,sw:screen.width,
sh:screen.height,scd:screen.colorDepth};screen.pixelDepth&&(b.spd=screen.pixelDepth);e.addonCMeter&&addonCMeter.PLID&&(b.tnscm_plid=addonCMeter.PLID);e.tnscm_cat&&(b.tnscm_cat=tnscm_cat);tnscm_adn&&(b.tnscm_adn=tnscm_adn);e.tnscm_pak&&(b.tnscm_pak=tnscm_pak);return b},send:function(){this.O?this.O():this.p()},p:function(){var e=0,f,h={},l=[];c.extend(h,this.aa());for(c.extend(l,this.b);l.length;)if(e+=1,(f=l.shift())||0===f)h["param"+e]=f;c.extend(h,l);p.send(this.url,b.c("send",h),this.C)}});c.extend(l.prototype,
{url:l.prototype.origin+"/pagestat/PageStatEntry"});return l}(L,C,I,F);M=function(p,c){function b(b){var c=this,e=["w","h"],f=["src"];this.h=this.w=null;p.a(b,function(b){var l,p=parseInt(b,10);if(!isNaN(p))l=e.shift();else if(b instanceof RegExp||"RegExp"==b.constructor.name)l=f.shift(),p=b;l&&(c[l]=p)});this.src||!this.w&&!this.h||(this.src=/./)}var q={};p.extend(b,{o:function(c){var f=!0,g=!1,q={Z:[],current:[]};p.a(c,function(c){c instanceof RegExp||"RegExp"==c.constructor.name?f=g=c.test(e.location.host):
f&&!g?q.Z.push(new b(c)):f&&g&&q.current.push(new b(c))});return q},embeds:function(b){var c=[],e=[],q=[];b=b||f;p.a(b.getElementsByTagName("embed"),function(b){for(var f=b.parentNode;f;){if("OBJECT"===f.nodeName){e.push(f);break}f=f.parentNode}-1===p.indexOf(q,b)&&c.push(b)});p.a(b.getElementsByTagName("object"),function(b){-1===p.indexOf(e,b)&&-1===p.indexOf(q,b)&&c.push(b)});return c},g:function(b){function c(b,e){p.a(q.A[b],function(b){b.check(e[0],e[1],e[2])&&(f=!0)});f&&p.a(q.M[b],function(b){b.check(e[0],
e[1],e[2])&&(f=!1)})}var e=[],f,v;p.a(b,function(b,l){f=!1;for(v in q.A)q.A.hasOwnProperty(v)&&c(v,b);f&&e.push(l)});return e}});p.extend(b.prototype,{check:function(b,c,e){return this.src&&!this.src.test(b)||this.w&&this.w!==c||this.h&&this.h!==e?!1:!0}});setTimeout(function(){q.A=b.o(c.c("templates:yes",[[/commersant\.ge\/uploads\//i],[/palitra\.ge\/baner\//i],[/picz\.ge\//i],[/\/html5\//i],[/weborama\./i],[/banner\.volynnews\.com/i],[/\.googlesyndication\.com\/simgad\//i],[/ads\.locals\.md\//i],
[/numbers\.md/i],[/\.zingan\.com\//i],[/cdn\.epom\.com\//i],[/\.vcdn\.biz\//i],[/\.rontar\.com\//i],[/adfox\.ru\//i],[/sourcefabric\.net\//i],[/media\.adrcdn\.com\/ads\//i],[/c8\.net\.ua\//i],[/\.adocean\.pl\//i],[/static\..*\.kcdn\.kz\//i],[/base\.kiwi\.kz\//i],[/dotua\.org\//i],[/advideo\.com\.ua\//i],[/admixer\.net/i],[234,200],[205,333],[205,280],[205,60],[203,70],[950,90],[760,90],[730,60],[730,90],[728,90],[640,90],[500,100],[468,120],[468,60],[320,76],[320,60],[300,600],[300,250],[300,240],
[285,130],[250,250],[240,400],[240,350],[240,200],[240,90],[234,60],[230,90],[230,60],[180,150],[160,600],[160,60],[150,60],[120,600],[120,240],[120,60],[/adriver\.ru/i],[/bannerka\.ua/i],[/reclama\./i],[/bbn\.img\.com\.ua/i],[/images\.rambler\.ru\/upl\//i],[/\/images\/.*\/.*\/.*\/.*300x250\./i],[/baner\./i],[/ad.*\.bigmir\.net/i],[/\/banners_files\/.*\./i],[/b\.ex\.ua\/.*\/.*\.swf/i],[/\/openx\/www\/images\/.*\./i],[/\/bnr\//i],[/\/adban\/.*\/.*\/.*\./i],[/informers\.sinoptik\.ua/i],[/adnet\.com\.ua\/banners\/.*\/.*\/.*\/.*\./i],
[/rose\.ixbt\.com/i],[/\/adv\//i],[/i\.holder\.com\.ua\/.*\/.*\/.*\/.*\./i],[/\/images\/.*\/.*\/.*\/.*\.swf$/i],/newposts\.ge/,[/\/banner/i],/ambebi\.ge/,[600,90],/kulinaria\.ge/,[300,300],[200,230],[620,90],/liberali\.ge/,[780,100],[390,100],/commersant\.ge/,[135,212],[220,110],[714,100],[275,130],[270,100],[272,105],[272,90],[270,107],/myauto\.ge/,[/static\.my\.ge\/myauto\/banners\//i],/\.ge/,[/\.ge\/www\/delivery\/afr\.php/i],[/\/www\/images\//i],[/baner/i],[640,100],/look\.tm/,[300,300],[258,
258],/adjaranet\.com/,[/banner/i],/horoskopi\.ge/,[300,300],/wom\.ge/,[300,100],/\.kz/,[728,200],[/\/banners/i],/allfun\.md/,[295,295],[476,102],/alltravel\.md/,[168,138],[215,155],[210,138],[394,88],/odessa-life\.od\.ua/,[/\/banners\//i],/volynnews\.com/,[460,145],[220,180],/moldova\.org/,[301,301],/tsamali\.ge/,[580,100],/i.*p.*n.*\.ge/,[/\/www\/images\/.*\./i],/forum\.ge/,[240,50],/file\.ge/,[/\/ad.*\./i],/\.md/,[/\/banner/i],/mail\.ru/,[/r\.mradx\.net\//i,300,300],[/r.*\.mail\.ru\/b.*\.gif$/i],
[/r.*\.mail\.ru\/b.*\.png$/i],[/r.*\.mail\.ru\/b.*\.jpg$/i],[/r.*\.mail\.ru\/b.*\.swf$/i],[/promoblocks\.ru/i],/football\.ua/,[/spadsmedia\.com\/www\/delivery\/afr\.php\//i],[/sportingbet\.host\.bannerflow\.com\//i],/total\.kz/,[1E3,115],[/\/gb\.php..*=/i],/namba\.net/,[468,90],[1E3,90],[200,350],/besplatka\.ua/,[300,300],[660,90],/nur\.kz/,[/\/advert\//i],/magnolia-tv\.com/,[668,60],[300,100],[/\/files\/ban\//i],[100,100],/companion\.ua\//,[960,90],/172\.16\.0\./,[/\.gif/i],[/\.png/i],[/\.swf/i],
[/\.jpeg/i],[/\.jpg/i],/ex\.ua/,[/ad_click/i],/aviso\.ua/,[/banner\.ool\.ua\//i]]))},4);setTimeout(function(){q.M=b.o(c.c("templates:no",[[/navaxudoru\.com\//i],[/hostingstrong\.com\//i],[/udsp-.*\.exe\.bid\//i],[/googlesyndication\.com\/sadbundle\//i],[/\.googlesyndication\.com\/pagead\//i],[/ismatlab\.com\//i],[/undefined$/i],[/ssp-rtb\.sape\.ru\//i],[/hobbiya\.com\.ua\/.*\.jpg$/i],[/viyar\.ua\/upload\//i],[/terraclicks\.com\//i],[/tabletki\.ua\//i],[/http:\/pagead\/ads/i],[/\/images\/products\//i],
[/\/products_image\//i],[/serving\.plexop\.net\//i],[/loikfuriss\.info\//i],[/data\.whicdn\.com\/images\//i],[/news\.abomus\.com.*\/sites\/default\/files\//i],[/pubonet\.fr\/show_i\.php/i],[/sofino\.ua\/img\//i],[/capital\.ua\/uploads\//i],[/ubercpm\.com\//i],[/tq\.abcdn\.bid\//i],[/adventori\.com\//i],[/installball\.com\//i],[/interesty\.net\//i],[/tengrinews\.kz\//i],[/ultra\.trophymanager\.com\//i],[/advinapps\.com\/ads/i],[/beelure\.com\//i],[/tmstorage\.com\//i],[/creativnost\.com\.ua\//i],[/\.adk2x\.com\//i],
[/tredman\.com\//i],[/kinopoisk\.ru\/film\//i],[/lyk9soryi3\.ru\//i],[/sld-ad\.ictv\.ua\//i],[/google\.com/i],[/cse\.google\.com\//i],[/\.bigmir\.net\/attach\//i],[/laguna\.ua\/production\//i],[/shoessale\.com\.ua\/.*\/thumb/i],[/reports\.sld\.kiev\.ua\//i],[/golosno\.com\.ua\/sites\/default\/files\/\/styles\//i],[/appwall-performance\.com\//i],[/government\.in\.ua\/code\.html/i],[/rfadver\.com\//i],[/^blob:http:\/\//i],[/dumskaya\.net\/pics\//i],[/rapidlinks\.org\//i],[/cheerless\.ru\//i],[/\.admixer\.net\/test1\/.*\/\..\[phId=/i],
[/\.ru\/.*zz.n=ololo_/i],[/\.vcdn\.biz\/.*\/type\.amlst\//i],[/orangeapps\.ru\//i],[/\.dotua\.org\/fgh\.js/i],[/\.googleapis\.com\//i],[/\.solvemedia\.com\//i],[/att.*\.i\.ua\/attach\//i],[/fr\.ybx\.io\/creative\//i],[/m6bgdvvgi8\.ru\//i],[/technologiestuart\.com\//i],[/\.vcdn\.biz\/.*\.ts$/i],[/qaylie\.ru\//i],[/technologiesaintjoseph\.com\//i],[/ctnsnet\.com\//i],[/myvideo\.ge\/movies\//i],[/site-analytics\.info\//i],[/algovid\.com\//i],[/agitated\.ru\//i],[/quentina\.ru\//i],[/servplay\.net\//i],
[/a\.c8\.net\.ua\/.*frame\.php/i],[/\.admixer\.net\/test1\/.*\/\..someClick=/i],[/orion-site\.com\/ajax/i],[/mwayss\.com\/ads/i],[/laredoute\.com\/products\//i],[/newstok\.ru\//i],[/anarrma\.ru\//i],[/gvt1\.com\//i],[/avalln\.ru\//i],[/ecpmrocks\.com\//i],[/ainulindal\.ru\//i],[/anghabar\.ru\//i],[/e-protected\.ru\//i],[/ad5ve\.com\//i],[/socauth\.privatbank\.ua\//i],[/atemda\.com\//i],[/atmsrv\.com\//i],[/meta\.vcdn\.biz\/.*_megogo/i],[/dotua\.org\/player\.js/i],[/cdn\.vm-corporate\.com\//i],[/xl415\.com\//i],
[/ad-maven\.com\//i],[/rev2pub\..*com\//i],[/tmdn.*\.com\//i],[/vindicosuite\.com\//i],[/telephone-store\.ru\//i],[/admtpmp.*\.com\//i],[/media\.adk2x\.com\//i],[/wheelpath\.com\//i],[/tools\.freehost\.com\.ua\//i],[/login\.snw\.media\//i],[/gocash01\.net\//i],[/akamai.*\.net\//i],[/clike\.su\//i],[/mtagmonetizationb\.com\//i],[/rafomedia\.com\//i],[/9f6qmf0hs\.ru\//i],[/cpmaffiliation\.com\//i],[/regiepublicitairecpm\.com\//i],[/cpmad.*\.com\//i],[/admediacpm\.com\//i],[/adserve/i],[/prd.*\.rontar\.com\/productiframe\.axd/i],
[/ato\.mx\//i],[/trafficmonsoon\.com\//i],[/\.com\/t\.php.*a=96/i],[/\.ua\/delivery\/afr\.php/i],[/rvfrm2010\.com\//i],[/touch1\.ru\//i],[/dataffastguru\.info\//i],[/playitviral\.com\//i],[/avenue\.center\//i],[/imgsrv\.io\//i],[/srv-statistics\.com\//i],[/cptlsrv\.com\//i],[/adsrvmedia\.net\//i],[/atdmt\.com\//i],[/wntg2x\.com\//i],[/memeglobal\.com\//i],[162,228],[/w55c\.net\//i],[/pipesarcade\.com\//i],[/groovitdigital\.com\//i],[/coolad9\.com\//i],[/blkz2x\.com\//i],[/servd2wn\.com\//i],[/yieldmedia\.net\//i],
[/adv679854\.ru\//i],[/semantichelper\.com\//i],[/connect\.ok\.ru\//i],[/bidvertiser\.com\//i],[/lightquartrate\.com\//i],[/8838d3aa4a6\.com\//i],[/secure\..*trk.*\.com\//i],[/r3\.c8\.net\.ua\/match_dsp\.php/i],[/delivery\.promo\.ge\//i],[/connexity\.net\//i],[/ad131m\.com\//i],[/merchenta\.com\//i],[/yu0123456\.com\//i],[/a4b80300d1f45b09e416e0934d52e2a2539\.com\//i],[/cured\.com\//i],[/wtp101\.com\//i],[/trk-xzz\.com\//i],[/de17a\.com\//i],[/getsecureweb\.com\//i],[/tesel8\.com\//i],[/everesttech\.net\//i],
[/imrk\.net\//i],[/h\.holder\.com\.ua\/f/i],[/starkcom\.net\/srv/i],[/r.*\.c8\.net\.ua\/getiframe\.php/i],[/localpages\.com\//i],[/leisure\.com\//i],[/teracreative\.com\//i],[/rernd\.com\//i],[/pheasantissueflummery/i],[/revsci\.net\//i],[/rtbidder\.net\//i],[/mediasoul\.net\//i],[/inb\.genorithm\.com\//i],[/\/image.*\/upload.*\//i],[/product.*picture/i],[/goo\.mx\//i],[330,220],[/kapcha/i],[/\.ria\..*\/photos\//i],[/img\/article\//i],[/design\.vesti-ukr\.com\//i],[/img\.com\//i],[/^http:\/\/undefined/i],
[/linkis\.com\//i],[/magnetix\..*\//i],[/ipvertising\.com\//i],[/shop_image/i],[/fotos\..*\/images\//i],[/sfera-tv\.com\.ua\/.*img\//i],[/ukrinform\.ua\/cgi-bin\//i],[/unian\..*\/cgi-bin\//i],[/iqalhcxcqz\.ru\//i],[/ritorno\.ru\//i],[/kleopatra0707\.com\//i],[/107\.23\..*\..*\//i],[/otzovik\.com\/product\//i],[/ftop\.ru\//i],[/osvita\.ua\/.*image/i],[/adroll\.com\//i],[/showbiza\.com\/.*photo/i],[/utro\.ua\/static\/adsense\//i],[/ikea\.com\//i],[/2mdn\.net\//i],[/easyhits4u\.com\//i],[/img\.4mama\.com\.ua\//i],
[/websteroidsapp\.com\//i],[/\.websearch\./i],[/searchsupporter\.info\//i],[/infoseekerapp/i],[/lookforithere\.info\//i],[/click2dad\.net\//i],[/aceadsys\.net\//i],[/bidswitch\.net\//i],[/targetix\.net\//i],[/people-group\.su\//i],[/mynagor\.com\//i],[/\.am15\.net\//i],[/fsua_items\/screen\//i],[/orbit\.lun\.ua\//i],[/hotline\.ua\/price\//i],[/all\.biz\/img\/.*\/catalog\/.*\./i],[/nxnxcaqicm/i],[/apis\.google\.com\//i],[/rmbn\.net\//i],[/adone\.ru\//i],[/advertbox\.us\//i],[/quikdisplay\.com\//i],
[/thespatialists\.com\//i],[/adimps-perf\.com\//i],[/tooljava\.org\//i],[/gettvwizard\.com\//i],[/mybb\.ru\//i],[/lollipop-network\.com\//i],[/playblasteroids\.com\//i],[/rbc\.ua\/static\//i],[/static\.com\//i],[/dumedia\.ru\//i],[/ticket\.net\//i],[/hoptopboy\.com\//i],[/porn\..*com\//i],[/kvihit\.com\//i],[/imagevenue\.com\//i],[/obrona\.org\//i],[/null$/i],[/interakt\.md\/content/i],[/gwallet\.com\//i],[/predictormedia\.com\//i],[/img\.ubr\.ua\/banners\/.*adsense\./i],[/dotomi\.com\//i],[/mobileadhost\.com\//i],
[/adsoptimizer\.net\//i],[/ad-sys\.com\//i],[/drivesection\.net\//i],[/tooldiv\.net\//i],[/livexjs\.net\//i],[/fellabooks\.net.*\/$/i],[/chocolatemx\.net\//i],[/aspire-guitar\.com\//i],[/golinkon\.info\//i],[/perfectnavigator\.com\//i],[/googleads/i],[/\.host\.bannerflow\.com\//i],[/serving.*\.com\//i],[/tracking\.m6r\.eu\//i],[/upload.*\/articles\//i],[/zedo\.com\//i],[/gogorithm\.com\//i],[/pdmayt\.com\//i],[/metrigo\.com\//i],[/vdaqyqwsrd\.ru\//i],[/qrdeom\.com\//i],[/tatami-solutions\.com\//i],
[/cloudfront\.net\//i],[/mrlmedia\.net\//i],[/mothernist\.hiro\.tv\//i],[/\.wlboon\.com\//i],[/admetaserver\.com\//i],[/\.ru\/show_banner\//i],[/tags\.qservz\.com\//i],[/neomion\.com\//i],[/^http:\/\/54\./i],[/x\.abk954\.com/i],[/creative\.xtendmedia\.com\//i],[/statisticsreporting\.com\//i],[/imhonet\.ru\/element\//i],[/mailsmania\.ru\//i],[/romilit\.com\//i],[/proligtb\.com\//i],[/brucelead\.com\//i],[/exebid\.ru\//i],[/koluty\.com\//i],[/\.retark\.com\//i],[/com\.adv\.vz\.ru\//i],[/webmoney\.ua\/tools\//i],
[/weropiy\.com\//i],[/\/games\/img\//i],[/flashgames.*\..*\//i],[/games\.info\//i],[/maikaru\.ru\/picture\//i],[/zvek\.com\.ua\/images\//i],[/get_qrapi/i],[/grandcapital\.ru\/static\/img/i],[/creativecdn\.com\//i],[/greefl\.com\//i],[/\.jutulep\.com\//i],[/baseflash\.com\//i],[/media\.tumblr\.com\//i],[/ssp\.adriver\.ru\/cgi-bin\/sync\.cgi/i],[/tractionize\.com\//i],[/secure\.demand-go\.com\//i],[/yourbucks\.org\//i],[/datamind\.ru\//i],[/fresh-cup\.org\//i],[/ad\.starlightmedia\.ua\//i],[/financecontext\.ru\//i],
[/attiveri\.com\/.* $/i],[/youtube\.com\//i],[/meta\.ua\/cell\.php/i],[/paramedjo\.com\//i],[/intencysrv\.com\//i],[/kilopog\.com\//i],[/gravyseals\.com\//i],[/media6degrees\.com\//i],[/lokomusic\.com\//i],[/tisa.ama\.com\/banner\.php/i],[/ministerial5\.com\//i],[/admailtiser\.com\//i],[/adgorithms\.com\//i],[/\/media\/gallery\//i],[/\.dotua\.org\/.*\/cover\/.*\.jpg$/i],[/wp-content\/upload/i],[/netdna-cdn\.com\//i],[/\/logo/i],[/adsmile\.biz\//i],[/medads\.ru\//i],[/gittigidiyor\.com\//i],[/oneund\.com\//i],
[/xmasdom\.com\//i],[/rainoftraffic\.info\//i],[/1xbet\.com\//i],[/clkrev\.com\//i],[/pub-fit\.com\//i],[/clicksor\.com\//i],[/sendspace\.com\//i],[/pgssl\.com\//i],[/rutarget\.ru\//i],[/datropy\.com\//i],[/dolka\.ru\//i],[/batanga\.net\//i],[/adorika\.net\//i],[/rfihub\.com\//i],[/loponop\.com\//i],[/palgames\.info\//i],[/play882\.info\//i],[/medialand\.ru\//i],[/funnygamezer\.info\//i],[/cloudgamezer\.com\//i],[/utrehter\.com\//i],[/hopto\.me\//i],[/intag\.co\/.* $/i],[/adk2\.com\//i],[/img\.admaster\.net\//i],
[/openx\.net\//i],[/firstadvplug\.com\//i],[/pirrit\.com\//i],[/metka\.ru\//i],[/tomobol\.com\//i],[/adzoook\.com\//i],[/adservingfree\.info\//i],[/drgo\.ru\//i],[/slopty\.ru\//i],[/tradedoubler\.com\//i],[/fastloca\.com\//i],[/hide4you\.com\//i],[/proxy\.net\//i],[/bannerhost\.ru\//i],[/bannercity\.ru\//i],[/m2pub\.com\//i],[/theseaapp\.com\//i],[/holisticmedicalwellness\.com\//i],[/qonenoj\.ru\//i],[/amazonaws\.com\//i],[/ipicture\.ru\/uploads\//i],[/reacten\.com\//i],[/thinglink\.me\//i],[/ad\.mail\.ru\/adi\//i],
[/k8media\.com\//i],[/notificatoin\.com\//i],[/co-co-co\.co\//i],[/\.dd34\.ru\//i],[/screenshot/i],[/yidop\.com\//i],[/pokitom\.com\//i],[/perfectmoney\.is\//i],[/20dollars2surf\.com\//i],[/bet-at-home\.com\//i],[/\.derploime\.com\//i],[/\.nekki\.ru\/banner\.php/i],[/tlvmedia\.com\//i],[/yoz5\.info\//i],[/game.*\.info\//i],[/jumbaexchange\.com\//i],[/media-servers\.net\//i],[/gnezdo\.ru\//i],[/quelliclub\.ru\/slider\//i],[/azd3\.info\//i],[/26sec\.com\//i],[/magicplayer\.torrentstream\.org\//i],[/refban\.com\//i],
[/microads\.ru\//i],[/scanmedios\.com\//i],[/trkclk\.net\//i],[/game.*\.com\//i],[/ro2\.biz\/ad\.php/i],[/gmodules\.com\//i],[/bremdy\.ru\//i],[/biglu\.ru\//i],[/pricora\.com\//i],[/twitbridge\.com\//i],[/resultsaccelerator\.net\//i],[/gayua\.com\//i],[/okitspace\.com\//i],[/yottos\.com\//i],[/teaserjs\.info\//i],[/wambacdn\.net\//i],[/adultadworld\.com\//i],[/adnetworkme\.com\//i],[/seethisinaction\.com\//i],[/cameleo\.ru\//i],[/exoclick\.com\//i],[/\.rubiconproject\.com\//i],[/\.adnetwork.*\.net\//i],
[/mediads\.info\//i],[/\.zanox\.com\//i],[/\.abnad\.net/i],[/reachjunction\.com\//i],[/\.e-viral\.com\//i],[/\.traffichaus\.com\//i],[/\.cmle\.ru\//i],[/datam\.com\//i],[/improvemedianetwork\.com\//i],[/adxplosions\.com\//i],[/mediaplex\.com\//i],[/redintelligence\.net\/request_content\.php/i],[/baserve\.net\/serve\.php/i],[/ktbt\.ru\/b\.php/i],[/sociomantic\.com\//i],[/yangot\.com\//i],[/static.*\.rutracker\.org\/iframe/i],[/partners\.otpusk\.com\/media\.php/i],[/image\.tsn\.ua\/media\/images/i],
[/nepalon\.com\//i],[/\.56.*\.net\/.*2\.php/i],[/\/vast\.php/i],[/ad.*\.adkserve\.com\//i],[/s\.holder\.com\.ua\/s/i],[/\.avazu\.net\//i],[/media\.glispa\.com\//i],[/squirrelsigdrs\.in\//i],[/overridingnichts\.in\//i],[/tecontx\.com\//i],[/ad-srvr\.com\//i],[/pswec\.com\//i],[/hubrus\.com\//i],[/beatwaretranscribing\.in\//i],[/ads\.people-group\.net/i],[/holyclick\.ru/i],[/\.bidsystem\.com/i],[/zpk200\.com\/serve/i],[/imgads\..*\.net\/afr\.php/i],[/\.btricl3\.ru\/js\/rot\.php/i],[/\.tizerbank\.com\//i],
[/\.plomihy\.com/i],[/static\.adv.*\.ru\/banners\//i],[/meta\.ua\/f_new\.asp/i],[/bdv\.bidvertiser\.com\/bidvertiser\.dbm/i],[/squirrelsigdrs\.in\/banners\/show\.php/i],[/code\.gif/i],[/calend\.ru\/img\/calendar\//i],[/hochu\.ua\/images\/articles\//i],[/tagcloud\.swf/i],[/myinfotopia\.com\//i],[/swfhttprequest\.swf/i],[/cityads\.ru\//i],[/\/www\/delivery\//i],[/z5x\.net\//i],[/adotube\.com\//i],[/lux-bn\.com\.ua\//i],[/criteo\.com\//i],[/autocompleteplus\.com\//i],[/etgdta\.com/i],[/soundmanager.*\.swf/i],
[/player\.swf/i],[/img\.traffim\.com\//i],[/sharedaddomain\.com\//i],[/avalala\.com\//i],[/meta\.ua\/img\/b\/roll_flv2\.swf/i],[/flowplayer/i],[/manifest\.f4m/i],[/radikal\.ru\//i],[/jsonlock\.net\//i],[/medbrowse\.com\.ua\/oops/i],[/\.yandex\./i],[/proxy\.com/i],[/ternopilmarket\.net\/modules\/goods\/images\//i],[/proxy.*\.media\.online\.ua\//i],[/\/picture.*_user\//i],[/img.*\.begun\.ru\//i],[/topdownloads\.ru\//i],[/gloker\.org\/upload/i],[/mycdn\.me\//i],[/gallery\.ru\//i],[/adxpansion\.com\//i],
[/creoads\.com\//i],[/bm\.img\.com\.ua\//i],[/a\.s3\.ua\//i],[/servedbyadbutler\.com/i],[/kidstaff\.net/i],[/counter\.png/i],[100,100],[/\/widget.*\//i],[/lh.*\.ggpht\.com\//i],[/mathtag\.com/i],[/kavanga\.ru/i],[/anonymizer\.com\.ua/i],[/\.adnxs\.com/i],[/\.yadro\.ru/i],[/\/img.*\/photo.*\//i],[/\/foto\//i],[/odnoklassniki\./i],[/static\/images/i],[/\.vk\.me\//i],[/rollingstone\.com\//i],[/\/interview.*\//i],[/\/post.*\//i],[/ads.*\.contentabc\.com\//i],[/ads.*\.msn\.com\//i],[/ads\.webmasters\.ru\//i],
[/ads\.vsisumy\.com\//i],[/ads\.trk4\.com\//i],[/ads\.trafficjunky\.net\//i],[/files\/images/i],[/ads\.porn.*\//i],[/4baby\.ua\/pictures/i],[/\.de\//i],[/\/thumb.*\//i],[/ad\.drugasmuga\.com\/ban\.php/i],[/\/public\/images\/gallery\//i],[/imgn\.dt00\.net\//i],[/lcads\.ru\//i],[/img\.terrikon\.info\//i],[/optimizedby\.brealtime\.com\//i],[/\/uploads\/posts/i],[/source\.mmi\.bemobile\.ua\/video\//i],[/avatar/i],[/\.pcads\.ru\//i],[78,78],[/uploads\.ru\//i],[88,40],[/fliphotos\.com\//i],[/rand_img\.php/i],
[/\/images_slandocomua\//i],[/chrome-extension:/i],[/about:blank/i],[/data:/i],[/gazeta\.ua\/img\/preview\//i],[/www\.ex\.ua\/show\//i],[/img\.gad\.org\.ua/i],[/1x1\.gif/i],[/vk\.jpg/i],[/c\.bigmir\.net/i],[/adlesse\.com/i],[/turzona\.com\.ua/i],[/kartinka\.com\.ua/i],[/totoro\.com\.ua/i],[/tas-ua\.toboads\.com/i],[/vk\.com/i],[/infrm\.weather\.ua\/image\//i],[/vk_banner/i],[/\.doubleclick\.net/i],[/twitter\.com/i],[/facebook\.com/i],[/captcha/i],[/images\.mob\.ua\//i],[/gorgeoushandbag\.com\//i],
[/imgg\.dt0.*\.net\//i],[/banner\.ua\/cgi-bin\/core\.fcgi/i],[/adverserve\.net/i],[/yield.*\.com\//i],[/tbn\.ru/i],[/adv\.fraza\.ua\//i],[/sinoptik\.ua\/_uploaded_files\/..\/..\/uft_................................\.jpg$/i],[/liga\.net\/www\/images\/.*\./i],[/x\.magnet\.kiev\.ua\/www\/images\/.*\./i],[/ads.*\.com\//i],/medtab\.com\.ua/,[/^http:\/\/medtab\.com\.ua\//i],/reitingi\.ge/,[/\/pictures\/image/i],/\.ge/,[/facebook\.com\//i],[/old\.amindi\.ge\/.*banner/i],/megogo\.net/,[/vcdn\.biz\/static\/.*\.jpg$/i],
/hostinghost14\.com\//,[/^$/i],/timpul\.md/,[150,60],/hotline\.ua/,[/\/img\/tx\//i],[120,60],/bona\.ua/,[/data\/small\//i],/kriminal\.tv/,[/image/i],/\.kz/,[/\/i\/0.*\.gif/i],/krisha\.kz/,[/\/i\/pro\//i],[70,50],[120,90],[60,50],/kolesa\.kz/,[60,50],[/\/idrive\//i],[/\/uploads\/content\//i],/magnolia-tv\.com/,[/pictures\/avatar\//i],/infohome\.com\.ua/,[250,250],/auto\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.jpg$/i],/sport\.ua/,[/sport\.ua\/images\//i],/autocentre\.ua/,[/autocentre\.ua\/images\//i],/terrikon\.com/,
[/\/fans\//i],/kievskaya\.com\.ua/,[/image\.tsn\.ua\//i],/mbox2\.i\.ua/,[/fsimg\.ru\//i],/uaua\.info/,[/\/pictures\//i],/telekritika\.ua/,[/telekritika\.ua.*\/imgs\//i],[/telekritika\.ua.*\/images\//i],/meteo\.ua/,[/meteo\.ua\/var\/banners\/favorites_ua\.jpg/i],/smartphone\.ua/,[/smartphone\.ua\/img\//i],[240,400],/itc\.ua/,[/itc\.ua\/files\/pic/i],/lissod\.com\.ua/,[/\/st_img\/flash\//i],/onlinetb\.com\.ua/,[200,200],/delo\.ua/,[/inf\.korrespondent\.net/i],[/informers\.ukr\.net/i],/sport-express\.ua/,
[/sport-express\.ua\/img\//i],/calend\.ru/,[/promo\.1000zakazov\.ru\//i],[/shkolazhizni\.ru\/img\/adv\//i],/bestdroid\.ru/,[/upload/i],/hnb\.com\.ua/,[/artimage/i],/biathlon\.com\.ua/,[/img\/ministerstvo\.gif/i],/gazeta\.ua/,[300,240],/mamaclub\.ua/,[300,250],/myradio\.ua/,[300,250],/oceni\.ua/,[250,250],/ava\.ua/,[240,400],/games\.bigmir\.net/,[/ads\..*\./i],/connect\.ua/,[300,240],/bilshe\.com/,[/banner/i],/realty\.mail\.ru/,[/img\.pre\.realty\.mail\.ru\/.*\.jpg$/i],/pogoda\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.jpg$/i],
/cards\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.png$/i],/hi-tech\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.png$/i],[/r.*\.mail\.ru\/b.*\.jpg$/i],/otvet\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.gif$/i],/health\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.gif$/i],[/r.*\.mail\.ru\/b.*\.jpg$/i],/deti\.mail\.ru/,[/r.*\.mail\.ru\/b.*\.jpg$/i],/mail\.ru/,[/ban\./i],[/\/adv\//i]]))},4);b.na=function(e,f){q.A=b.o(c.c("templates:yes",e));q.M=b.o(c.c("templates:no",f))};return b}(C,I);(function(p,c,b,q,l,h){var g=(p=(p=e.performance)?p.timing:
null)?new Date(p.navigationStart||p.connectStart):new Date,z=navigator.userAgent,v=/android|mobi|mini|blackberry|samsung|bada|nokia|series|symb(ian|os)|playstation/i.test(z),s=!(top===self||top===e),w=location.href.replace(location.hash,"");e.__cm||(p=e.__cm=[],b.extend(p,{on:q.on}));if(-1==b.indexOf(e.__cm,b.r())){tnscm_adn=tnscm_adn||[];0>b.indexOf(tnscm_adn,"inline_cm")&&b.$(f,function(c){if(8===c.nodeType&&"MMI CMeter"===b.trim(c.nodeValue))return!0})&&tnscm_adn.push("inline_cm");var n=new l("video",
{e:[],n:[],W:[],G:0,t:function(){var k=/MSIE/.test(z),f=/iPhone OS 3/.test(z);if(!s||c.work_in_frame)this.url=location.protocol+"//"+c.video.url,this.C=e.opera||k||f?"GET":"POST",setInterval(function(){n.g()},1E3*c.ads.scan_frequency),b.D(this.k,this.m),n.g()},k:function(){this.G=1},m:function(){this.G=0},append:function(c){if(-1==b.indexOf(n.n,c)){var e=n.n.push(c);n.K(c,e-1);n.X(c)}},g:function(){b.a(f.getElementsByTagName("video"),n.append)},K:function(b,e){n.W[e]={duration:b.duration,width:b.clientWidth,
height:b.clientHeight,src:b.currentSrc&&"data:video"==b.currentSrc.substring(0,10)?c.juke_host[0]:b.currentSrc,id:n.U()+"."+e}},X:function(c){function e(a){var b="was"+a;"undefined"==typeof f[b]&&n.e[d].push(a);f[b]=!0}function a(){f.d=0;f.q=0;n.e[d]=[]}var d=b.indexOf(n.n,c),f=n.n[d],g;n.e[d]=n.e[d]||[];b.a(["canplay","play","timeupdate","pause"],function(f){b.on(c,f,function(c){"canplay"==c.type&&(e("READY"),a());"play"==c.type&&e("PLAY");"pause"==c.type&&a();"timeupdate"==c.type&&-1==b.indexOf(n.e[d],
"ONLINE")&&n.e[d].push("ONLINE")})});a();3<f.readyState&&e("READY");g=setInterval(function(){null===f.parentNode?clearInterval(g):n.ma(d)},1E3)},ma:function(c){var e=new Date,a={},d=n.n[c];d.q+=1;d.q>=d.d&&!(1>n.e[c].length)&&(-1<b.indexOf(n.e[c],"ONLINE")&&(a.currentTimer=d.d,10<=d.d&&(d.d+=5),10>d.d&&(d.d+=1),60<d.d&&(d.d=60),d.q=0),a.events=n.e[c],n.K(d,c),b.extend(a,n.W[c]),a.tabStatus=n.G,n.b.result=encodeURIComponent("["+JSON.stringify(a)+"]"),d.ta=e,n.send(),n.e[c]=[])}}),y=new l("banners",
{u:[],T:0,ia:1,S:[],t:function(){var f=/MSIE/.test(z),g=/iPhone OS 3/.test(z);if(!s||c.work_in_frame)this.C=e.opera||f||g?"GET":"POST",setInterval(function(){y.g(y.N)},1E3*c.ads.scan_frequency),this.b.sr=1,b.D(this.k,this.m),y.g(y.N)},F:function(){this.referrer=w;this.T=0;this.u=[];this.ia++},k:function(){s?this.b.sr=2:delete this.b.sr},m:function(){this.b.sr=1},g:function(k){function g(a,c){function d(a){var b,c="",e="div[class*=brending];a[class*=branding];div[id*=branding] > a;div[class*=branding] > a;a[id*=branding];a".split(";"),
k=e.length;if("A"==a.tagName)return a.getAttribute("href");for(a==f.body&&(c="body >");k--;)if(b=a.querySelectorAll(c+e[k]),!(3<b.length)&&b[0])return b[0].getAttribute("href")}function k(a){var b=((a.currentStyle||e.getComputedStyle(a,null)||{}).backgroundImage||"").match(p);b&&b[1]&&300<=a.offsetWidth&&240<=a.offsetHeight&&(b=b[1].split('"').join(""),b!=e.location.href.split("#")[0]&&l.push({node:a,bg:b,cl:d(a)}))}var h=a.childNodes||[],m=h.length,l=g.items||[],n=["head","script","style"],x;if(0>=
c)q&&(x=f.getElementById("branding_wrap")||f.getElementById("html-id"))&&(q=!1,g(x,4));else{for(g.items=l;m--;)1==h[m].nodeType&&0>b.indexOf(n,h[m].tagName.toLowerCase())&&(k(h[m]),g(h[m],c-1));return g.items}}function a(d){function f(a){var d=b.I(a),e=b.J(a);e.w<=c.ads.width||e.h<=c.ads.height||(a.H=d,l.push(a),n.push([d,e.w,e.h]))}function k(a){return a.addonCMeter&&a.addonCMeter.PLID?!0:!1}b.a(d.images||d.getElementsByTagName("img"),f);b.a(d.getElementsByTagName("svg"),f);b.a(d.getElementsByTagName("video"),
f);b.a(h.embeds(d),f);b.a(d.getElementsByTagName("iframe"),function(c){var d,g=!1;b.ha(c)?(d=c.contentWindow||c.contentDocument.parent,d.__cm&&-1!=b.indexOf(d.__cm,b.r())||k(d)||(b.a(d.document.getElementsByTagName("script"),function(a){a=b.I(a);/source\.mmi\.bemobile\.ua\/cm\/(cmeter_an|cm)\.js/.test(a)&&(g=!0)}),g||a(b.ca(c)))):k(e)||f(c)})}var d=[],m=y.g.Y=y.g.Y||[],l=[],n=[],p=/\s*url\(\s*([^\)]+)\s*\)\s*/i,q=!0;-1===b.indexOf(m,k)&&m.push(k);a(f);for(b.a(h.g(n),function(a){d.push(l[a])});m.length;)m.shift()(d,
g(f,4))},N:function(c,e){function a(){h=q.c("addDisappearBanner",h);h=q.c("banners",h);g.b.result=encodeURIComponent("["+h.join(",")+"]");h.length&&g.send()}function d(a,b,c,d){var e="",e='{"link":"'+a+'", "pos":"'+b;c&&(e+='", "cl":"'+c);d!=E&&(e+='", "bt":"'+d);return e+'"}'}function f(a){return-1==g.S.indexOf(a)?(g.S.push(a),!0):!1}var g=this,h=[],l={};b.a(e,function(b){var c,e=b.bg;if(f(e)){if("data:image/"==e.substr(0,11).toLowerCase()){if(l.hasOwnProperty(e))return;c=new Image;c.src=e;if(33>
c.width&&33>c.height){l[e]=c;return}}h.push(d(e,0,b.cl,2));50<=h.length&&(a(),h=[])}});b.a(c,function(c){if(f(c.H)){var e=c.H,k=b.ba(c),l;if(b.ka(c))l=b.J(c),c=b.ea(c).top+b.da(l)+l.h;else{if(-1===b.indexOf(g.u,c)){g.u.push(c);return}c=-1}h.push(d(e,c,k));50<=h.length&&(a(),h=[])}});a()}}),A=new l("timer",{t:function(){this.l=null;if(!s||c.work_in_frame&&!c.addon_disable_frame_timers)this.Q=[],b.extend(this.Q,c.timer.pings),b.load(this.P),b.v(this.v),b.D(A.k,A.m)},ja:function(){try{return e.top.__cm?
(clearInterval(this.interval),!1):!0}catch(b){return!0}},O:function(){var b=new Date,c=b-g;this.b[1]=Math.round(((this.s||b)-(this.B||g))/1E3);this.b[2]=this.l;this.b[4]=Math.round(c/1E3);if(!s||this.ja())this.p(),this.p.time=b},V:function(){var b=new Date,e=Math.round((b-this.B)/1E3),b=Math.round((b-(this.p.time||0))/1E3)>=c.timer.frequency;this.B&&b&&(e>=60*c.timer.stop_after&&clearInterval(this.interval),e>=c.timer.pings[0]?(this.send(),1===c.timer.pings.length&&(this.la=c.timer.pings[0]-this.L),
this.L=c.timer.pings.shift()):0==e%this.la?(this.send(),this.L=e):this.b[2]!==this.l&&this.send())},P:function(b){this.b[3]=b-g;this.v()},k:function(){var b=new Date;if(!this.s)if(this.B=b,v){var e=this;setTimeout(function(){y.T+y.u.length||e.V()},1E3*c.ads.scan_frequency+1E3)}else this.interval=setInterval(this.V,1E3),this.send()},m:function(){var b=new Date;this.s||(this.s=b,v||this.send(),clearInterval(this.interval))},v:function(){var c=f.body,e=f.documentElement,a=b.fa(),d="clientHeight"in e?
e.clientHeight:0;c&&(d="CSS1Compat"===f.compatMode?e.clientHeight:c.clientHeight);a+d>=this.l&&(this.l=a+d)},F:function(){this.l=null;this.s=E;this.referrer=w;g=new Date;clearInterval(this.interval);if(!s||c.work_in_frame&&!c.addon_disable_frame_timers)b.load(this.P),this.b[3]=0,c.timer.pings=[],b.extend(c.timer.pings,this.Q),this.k()}});setInterval(function(){var b=location.href.replace(location.hash,"");w!==b&&(y.F(),A.F(),w=b)},1E3*c.timer.check_location_timer||1E3);e.__cm.push(b.r())}})(L,F,C,
I,O,M)})()})(window,document);
